name: deploy
on:
  push: 
    branches: [ main, develop ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout backend
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # - name: Setup Seed TypeORM
      #   run: npm run seed:run

      - name: Deploy to heroku
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "cloth-service" #Must be unique in Heroku
          heroku_email: "lnjoy3306@gmail.com"